In [ ]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense,Activation,Flatten,Dropout
from keras.layers import Conv2D,MaxPooling2D

data=np.load('dataChestXray.npy')
target=np.load('targetChestXray.npy')

def loadingCNN():
    model=Sequential()
    model.add(Conv2D(32,(3,3),input_shape=data.shape[1:]))
    model.add(Activation('relu'))
    model.add(MaxPooling2D(pool_size=(2,2)))
    model.add(Dropout(0.5))

    model.add(Conv2D(32,(3,3)))
    model.add(Activation('relu'))
    model.add(MaxPooling2D(pool_size=(2,2)))
    model.add(Dropout(0.5))

    model.add(Conv2D(64,(3,3)))
    model.add(Activation('relu'))
    model.add(MaxPooling2D(pool_size=(2,2)))
    model.add(Dropout(0.5))

    model.add(Flatten())

    model.add(Dense(128,activation='relu'))
    model.add(Dropout(0.5))
    model.add(Dense(2,activation='softmax'))

    model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
    model.load_weights('Pnemonia_predictions_using_chest_xray_99.20.h5')
    return model

loadingCNN()

<Sequential name=sequential_1, built=True>

In [ ]:
import cv2 as cv
import os

testPath='Testimages'
imageNames=os.listdir(testPath)
model=loadingCNN()
category={0:'Normal',1:'Pnemonia'}

for imageName in imageNames:
    imagePath=os.path.join(testPath,imageName)
    image=cv.imread(imagePath)
    grayImage=cv.cvtColor(image,cv.COLOR_BGR2GRAY)
    resized=cv.resize(grayImage,(128,128))
    normalized=resized/255
    reshaped=np.reshape(normalized,(1,128,128,1))
    result=model.predict(reshaped)
    label=np.argmax(result,axis=1)[0]
    prob=np.max(result,axis=1)[0]
    prob=round(prob,2)*100
    cv.putText(image,str(category[label]),(100,100),cv.FONT_HERSHEY_SIMPLEX,3,(255,255,255),2)
    cv.putText(image,str(category[label]),(100,200),cv.FONT_HERSHEY_SIMPLEX,3,(255,255,255),2)
    cv.imshow('LIVE',image)
    cv.waitKey(5000)
    print(result)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 726ms/step
[[0.9316023  0.06839769]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
[[0.1607945  0.83920556]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step
[[0.18922134 0.8107787 ]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step
[[0.37178096 0.628219  ]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step
[[0.9399022 0.0600978]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step
[[0.837872   0.16212802]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step
[[0.93874246 0.0612576 ]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step
[[0.36567286 0.6343271 ]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
[[0.62309265 0.3769073 ]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
[[0.12392261 0.8760775 ]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
[[0.8286202  0.17137973]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
[[0.05559871 0.9444013 ]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
[[0.8097701  0.19022985]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
[[0.51051927 0.4894807 ]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
[[0.494094   0.50590605]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
[[0

KeyboardInterrupt: 